In [67]:
import pandas as pd
from tqdm import tqdm
from dotenv import load_dotenv
from openai import OpenAI
from sqlalchemy import create_engine
from litellm import completion
from unidecode import unidecode
from typing import List, Literal
from pydantic import BaseModel, Field
from typing import List, Optional
import json
import ast
import re

MODEL = "gpt-4.1-mini"

load_dotenv(override=True)
openai = OpenAI()

In [68]:
engine = create_engine('mysql+pymysql://dev:dev@localhost:3306/recipe_app')

### Get Unique List of ingredients

In [76]:
QUERY = """
    SELECT ingredients FROM recipes_staging
"""

df = pd.read_sql_query(QUERY, con=engine)
unique_items = set(
    item
    for sublist in df["ingredients"]
    for item in ast.literal_eval(sublist)
)
len(unique_items)

12508

In [77]:
# Cleaning by patterns
phrases = ["cover", "skinned", "peeled", "ounce", "frozen", "cooked", "cup", "bone", "gram", "halved", "plus", "pound", "thick", "skinless", "grilled skinless"]

digits = {item for item in unique_items if any(char.isdigit() for char in item)}
long_items = {item for item in unique_items if len(item) > 25}
short_items = {item for item in unique_items if len(item) <= 2}
or_items = {item for item in unique_items if "or " in item or " or" in item}
and_items = {item for item in unique_items if "and " in item or " and" in item}
of_items = {item for item in unique_items if "of " in item or " of" in item}
phrases_items = {item for item in unique_items if any(phrase == item for phrase in phrases)}

# Remove them from the set
unique_items -= digits | long_items | short_items | or_items | and_items | of_items# | phrases_items

In [78]:
ingredients = list(unique_items)
len(unique_items)

8714

In [73]:
len("sweetened flaked coconut")

24

### Define Models for expected LLM output

In [29]:
Binary = Literal[0, 1]




class IngredientMapping(BaseModel):
    original: str = Field(
        description="Original ingredient string provided by the user"
    )

    simplified: Optional[str] = Field(
        description=(
            "Canonical simplified ingredient name. "
            "Null if the input is not a valid standalone ingredient."
        ),
        default=None
    )


class IngredientNormalizationResponse(BaseModel):
    mappings: List[IngredientMapping]


class IngredientClassification(BaseModel):
    ingredient: str = Field(
        ...,
        description="Ingredient name normalized to lowercase singular form where appropriate"
    )

    vegan: Binary = Field(
        ...,
        description="1 if vegan, otherwise 0"
    )

    vegetarian: Binary = Field(
        ...,
        description="1 if vegetarian, otherwise 0"
    )

    gluten_free: Binary = Field(
        ...,
        description="1 if gluten free, otherwise 0"
    )

    halal: Binary = Field(
        ...,
        description="1 if halal, otherwise 0"
    )

    kosher: Binary = Field(
        ...,
        description="1 if kosher, otherwise 0"
    )

    keto_friendly: Binary = Field(
        ...,
        description="1 if keto friendly, otherwise 0"
    )


class IngredientClassificationBatch(BaseModel):
    ingredients: List[IngredientClassification] = Field(
        ...,
        description="List of classified ingredients"
    )

### 1. Simplify ingredients list

In [24]:
simplify_system_prompt = """
You are an ingredient normalization engine.

Your task is to simplify ingredient names into their canonical culinary form.

You must always return the original ingredient and the simplified name as in the schema.

Rules:

1. Remove:
- marketing adjectives
- quality descriptors
- preparation adjectives that do not change ingredient identity
- color descriptors when they are only stylistic variants
- unnecessary intensifiers
- brand-like wording

2. Do not change already simple and clear ingredients. Just keep them the same.
Examples:
- potatoes
- bacon
- ham
- onion


Examples:
- "premium tequila" -> "tequila"
- "roasted chicken" -> "chicken"
- "fresh parsley" -> "parsley"
- "black soy sauce" -> "soy sauce"

3. DO NOT over-normalize.
If removing a word changes the ingredient into a different ingredient, preserve it.

Examples:
- "egg whites" -> "egg whites"
- "olive oil" -> "olive oil"
- "sweet potato" -> "sweet potato"
- "coconut milk" -> "coconut milk"
- "rice vinegar" -> "rice vinegar"

4. Preserve:
- important ingredient identity
- ingredient subtype when it changes culinary meaning
- compound ingredient names
- protected culinary terms

Examples:
- "soy sauce" -> "soy sauce"
- "fish sauce" -> "fish sauce"
- "brown sugar" -> "brown sugar"
- "heavy cream" -> "heavy cream"

5. Return ONLY valid JSON matching the schema.

6. Keep output lowercase.

7. Never invent ingredients.

8. If uncertain, preserve more information instead of less.

9. Some inputs may not be actual ingredients.
These may be:
- preparation fragments
- ingredient modifiers
- cuts without ingredient identity
- standalone descriptors
- accidental parsing artifacts

Examples:
- "skin-on" -> null
- "thigh skin" -> null
- "low-sodium" -> null
- "boneless" -> null
- "peeled and deveined" -> null

Only if you are fully certain that the input is not a valid standalone culinary ingredient, return null.

The goal is culinary canonicalization, not aggressive shortening.
"""

In [26]:
def normalization_process_batch(ingredients_list_chunk, system_prompt):
    user_prompt = f"""
    Normalize the following ingredients.

    Return one normalization object per ingredient.

    Ingredients:
    {chr(10).join(f"- {ingredient}" for ingredient in ingredients_list_chunk)}

    Important:
    - Preserve original ingredient text exactly.
    - Return results in the same order as input.
    - Do not skip ingredients.
    """

    messages = [
            {"role": "system", "content": system_prompt},
            {"role": "user", "content": user_prompt},
        ]

    response = completion(model=MODEL, messages=messages, response_format=IngredientNormalizationResponse)
    content = response.choices[0].message.content
    data = json.loads(content)

    return {
        item["original"]: item["simplified"]
        for item in data["mappings"]
    }

    return reply.model_dump()

In [27]:
def normalize_ingredients(ingredients_list, batch_size=75):
    output_dict = {}
    for i in tqdm(range(0, len(ingredients_list), batch_size)):
        batch = ingredients_list[i:i+batch_size]
        batch_dict = normalization_process_batch(batch, simplify_system_prompt)
        output_dict.update(batch_dict)
    return output_dict

In [30]:
normalized_ingredients = normalize_ingredients(ingredients)

100%|██████████| 61/61 [15:01<00:00, 14.77s/it]

In [44]:
df_normalized = pd.DataFrame(
    normalized_ingredients.items(),
    columns=["original", "simplified"]
)
path_normalized = r"../data/ingredient_normalized.csv"
df_normalized.to_csv(path_normalized, index=False)
df_normalized.head()

          original       simplified
0  roasted pepitas          pepitas
1    coarsely kale             kale
2      dill stalks      dill stalks
3  halloumi cheese  halloumi cheese
4     frozen hatch            hatch

In [50]:
normalized_list = df_normalized["simplified"].unique().tolist()
# normalized_list.remove("")
len(normalized_list)

3126

### 2. Classify the normalized list

In [51]:
classify_system_prompt = """You are a food science and dietary classification expert.
Classify each ingredient with strict accuracy. Return ONLY valid JSON matching the schema.
Do not omit fields.

Rules:
- vegan: 1 only if contains NO animal products (no meat, poultry, seafood, dairy, eggs, honey, gelatin, lard, suet, animal rennet, etc.)
- vegetarian: 1 if no meat/poultry/seafood but dairy/eggs are OK. Always >= vegan value.
- gluten_free: 1 if no wheat, barley, rye, spelt, kamut, triticale, or derivatives (bread, pasta, beer/malt, bulgur, farro, couscous, semolina, seitan, soy sauce, most flour, croutons, etc.)
- keto_friendly: 1 if very low carb (generally <5g net carbs per typical serving). Sugar, rice, pasta, bread, most fruits, potatoes, corn, beans, legumes = 0.
- halal: 1 if permissible under Islamic law (no pork/pork derivatives, no alcohol/wine/beer, no blood, only properly slaughtered animals). Plain plant foods are halal=1. Gelatin is 0 unless specified halal.
- kosher: 1 if permissible under Jewish dietary law (no pork, no shellfish/crustaceans, no mixing meat+dairy in same dish — but for standalone ingredient: pork=0, shellfish=0, non-kosher slaughter=0). Plain plant foods are kosher=1.

Special cases:
- Alcohol (wine, beer, spirits): vegan=1/vegetarian=1 usually, halal=0, keto varies
- Honey: vegan=0, vegetarian=1
- Dairy: vegan=0, vegetarian=1
- Eggs: vegan=0, vegetarian=1
- Pork (ham, bacon, lard, prosciutto, salami, pepperoni, capicola, etc.): halal=0, kosher=0
- Shellfish/crustaceans (shrimp, crab, lobster, clam, oyster, mussel, scallop): kosher=0
- Gelatin (unless specified halal/kosher): halal=0, kosher=0
- Rennet (animal): kosher is complex but default 0 for hard cheeses unless specified
- Bread, pasta, crackers, flour tortillas, couscous, bulgur, farro, seitan: gluten_free=0
- Rice, corn, potatoes: gluten_free=1
- Beer/malt beverages: gluten_free=0 (unless specified gluten-free)
"""

In [52]:
def classify_process_batch(ingredients_list_chunk, system_prompt=classify_system_prompt):
    user_prompt = f"""
    Classify the following ingredients.

    Return one classification object per ingredient.

    Ingredients:
    {chr(10).join(f"- {ingredient}" for ingredient in ingredients_list_chunk)}

    Important:
    - Preserve original ingredient text exactly.
    - Return results in the same order as input.
    - Do not skip ingredients.
    - Use only 0 or 1 values.
    """

    messages = [
            {"role": "system", "content": system_prompt},
            {"role": "user", "content": user_prompt},
        ]

    response = completion(model=MODEL, messages=messages, response_format=IngredientClassificationBatch)
    reply = response.choices[0].message.content
    data = json.loads(reply)
    output_df = pd.DataFrame(data["ingredients"])
    return output_df

In [31]:
def classify_ingredients(ingredients_list, batch_size=50):
    output_df = pd.DataFrame()
    for i in tqdm(range(0, len(ingredients_list), batch_size)):
        batch = ingredients_list[i:i+batch_size]
        batch_df = classify_process_batch(batch)
        output_df = pd.concat([output_df, batch_df], ignore_index=True)
    return output_df

In [32]:
classified_df = classify_ingredients(normalized_list)

100%|██████████| 61/61 [28:53<00:00, 28.42s/it]

In [72]:
path = r"../data/classified_ingredients.csv"
classified_df.to_csv(path, index=False)

### 3. Join two dataframes into comprehensive mapping and save as `ingredients_main` table

In [4]:
path_final = r"../data/ingredient_main.csv"

In [73]:
df_final = pd.merge(df_normalized, classified_df, how='left', left_on='simplified', right_on='ingredient')
df_final_clean = df_final.dropna().drop(columns=['simplified'])
df_final_clean.to_csv(path_final, index=False)
df_final_clean.head()

,original,ingredient,vegan,vegetarian,gluten_free,halal,kosher,keto_friendly
0,bbq rub,bbq rub,1.0,1.0,0.0,1.0,1.0,1.0
1,toasted almonds,almonds,1.0,1.0,1.0,1.0,1.0,1.0
2,lean turkey,turkey,0.0,0.0,1.0,1.0,1.0,1.0
3,red grapefruits,grapefruits,1.0,1.0,1.0,1.0,1.0,0.0
4,red salmon,red salmon,0.0,0.0,1.0,1.0,0.0,1.0

In [62]:
df_classified = pd.read_csv(path_final)

def clean_text(x):
    if pd.isna(x):
        return x

    x = str(x)

    # remove control characters like 
    x = re.sub(r"[\x00-\x1F\x7F-\x9F]", "", x)

    # normalize unicode accents (ç, é, etc.)
    x = unidecode(x)

    # normalize case and whitespace
    x = x.lower().strip()

    return x

#df_classified["ingredient_normalized"] = df_classified["ingredient"].apply(clean_text)

# df_classified = df_classified.drop_duplicates(
#     subset=["ingredient_normalized"],
#     keep="first"
# )

#df_classified = df_classified.drop(columns=["ingredient_normalized"])

df_classified.head()

,original,ingredient,vegan,vegetarian,gluten_free,halal,kosher,keto_friendly
0,bbq rub,bbq rub,1.0,1.0,0.0,1.0,1.0,1.0
1,toasted almonds,almonds,1.0,1.0,1.0,1.0,1.0,1.0
2,lean turkey,turkey,0.0,0.0,1.0,1.0,1.0,1.0
3,red grapefruits,grapefruits,1.0,1.0,1.0,1.0,1.0,0.0
4,red salmon,red salmon,0.0,0.0,1.0,1.0,0.0,1.0

In [63]:
test = df_classified[df_classified['ingredient'] == 'onions']

In [64]:
test

,original,ingredient,vegan,vegetarian,gluten_free,halal,kosher,keto_friendly
11,canned onions,onions,1.0,1.0,1.0,1.0,1.0,1.0
316,white onions,onions,1.0,1.0,1.0,1.0,1.0,1.0
681,boiling onions,onions,1.0,1.0,1.0,1.0,1.0,1.0
2088,vidalia onions,onions,1.0,1.0,1.0,1.0,1.0,1.0
2170,sweet onions,onions,1.0,1.0,1.0,1.0,1.0,1.0
2321,frozen onions,onions,1.0,1.0,1.0,1.0,1.0,1.0
2569,onions,onions,1.0,1.0,1.0,1.0,1.0,1.0
2924,sautéed onions,onions,1.0,1.0,1.0,1.0,1.0,1.0

In [65]:
# This looks for "ham" anywhere inside the 'original' column
df_classified[df_classified['original'].str.contains('white onion', na=False)]

,original,ingredient,vegan,vegetarian,gluten_free,halal,kosher,keto_friendly
316,white onions,onions,1.0,1.0,1.0,1.0,1.0,1.0
3929,white onion,onion,1.0,1.0,1.0,1.0,1.0,1.0

In [66]:
df_classified.to_sql(
            name="ingredients_main",
            con=engine,
            if_exists="append",
            index=False,
            method="multi"
        )

4023

In [4]:
text = "pork picnic roast"
len(text)

17

In [ ]:
["soy sauce", "italian-style salad dressing", "barbeque sauce", "vegetable oil", "garlic", "seasoning to taste", "salt to taste", "to taste", "black pepper to taste", "beef sirloin steak"]